version: "3"
services:
  reverseproxy:
    image: vspreys/reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-user:
    image: vspreys/udacity-restapi-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      UDAGRAM_POSTGRESS_USERNAME: $UDAGRAM_POSTGRESS_USERNAME
      UDAGRAM_POSTGRESS_PASSWORD: $UDAGRAM_POSTGRESS_PASSWORD
      UDAGRAM_POSTGRESS_DATABSE: $UDAGRAM_POSTGRESS_DATABSE
      UDAGRAM_POSTGRESS_HOST: $UDAGRAM_POSTGRESS_HOST
      UDAGRAM_AWS_REGION: $UDAGRAM_AWS_REGION
      UDAGRAM_AWS_PROFILE: $UDAGRAM_AWS_PROFILE
      UDAGRAM_AWS_MEDIA_BUCKET: $UDAGRAM_AWS_MEDIA_BUCKET
      UDAGRAM_JWT_TOKEN: $UDAGRAM_JWT_TOKEN
      URL: "http://localhost:8100"
  backend-feed:
    image: vspreys/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      UDAGRAM_POSTGRESS_USERNAME: $UDAGRAM_POSTGRESS_USERNAME
      UDAGRAM_POSTGRESS_PASSWORD: $UDAGRAM_POSTGRESS_PASSWORD
      UDAGRAM_POSTGRESS_DATABSE: $UDAGRAM_POSTGRESS_DATABSE
      UDAGRAM_POSTGRESS_HOST: $UDAGRAM_POSTGRESS_HOST
      UDAGRAM_AWS_REGION: $UDAGRAM_AWS_REGION
      UDAGRAM_AWS_PROFILE: $UDAGRAM_AWS_PROFILE
      UDAGRAM_AWS_MEDIA_BUCKET: $UDAGRAM_AWS_MEDIA_BUCKET
      UDAGRAM_JWT_TOKEN: $UDAGRAM_JWT_TOKEN
      URL: "http://localhost:8100"
  frontend:
    image: vspreys/udacity-frontend
    ports:
      - "8100:80"
